; ==========================================
; PLATFORMIO - ARDUINO UNO
; ==========================================

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; ==========================================
; BIBLIOTECAS
; ==========================================

lib_deps =
    Keypad
    LiquidCrystal
